import Head from "next/head";

import { useGetPostByIdQuery } from "@/services/post";

export default function ByID() {
  // const { data: responseInfo } = useGetAllPostQuery();
  const getData = useGetPostByIdQuery(5);

  if (getData.isLoading) return <div>Loading...</div>;
  if (getData.isError) return <h2>An error occured{getData.error.error}</h2>;

  return (
    <>
      <Head>
        <title>jsonplaceholder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Redux Toolkit - RTK Query (Get By ID)</h1>
            <div style={{ fontWeight: "normal", margin: "1rem" }}>
              <h3>
                {getData.data.id} {getData.data.title}
              </h3>
              <p>{getData.data.body}</p>
              <hr />
            </div>
      </div>
    </>
  );
}
