import Head from "next/head";

import { useDeletePostMutation } from "@/services/post";

export default function PostDelete() {
  // const { data: responseInfo } = useGetAllPostQuery();
  const [deleteData, getData] = useDeletePostMutation();

  console.log("Success: ",getData.isSuccess);
  
  if (getData.isLoading) return <div>Loading...</div>;
  if (getData.isError) return <h2>An error occured{getData.error.error}</h2>;

  return (
    <>
      <Head>
        <title>jsonplaceholder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Redux Toolkit - RTK Query (Delete Data)</h1>
          <button onClick={() => {deleteData(2)}}>Delete Post</button>
      </div>
    </>
  );
}
