import Head from "next/head";

import { useCreatePostMutation } from "@/services/post";

export default function PostCreate() {
  // const { data: responseInfo } = useGetAllPostQuery();
  const [createData, getData] = useCreatePostMutation();

  console.log("Success: ",getData.isSuccess);
  console.log("Data: ",getData.data);
  
  if (getData.isLoading) return <div>Loading...</div>;
  if (getData.isError) return <h2>An error occured{getData.error.error}</h2>;

  const item = {
   title: "coba title",
   body: "coba body",
   userId: 101,
  }

  return (
    <>
      <Head>
        <title>jsonplaceholder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Redux Toolkit - RTK Query (Create Data)</h1>
          <button onClick={() => {createData(item)}}>Create Post</button>
      </div>
    </>
  );
}
