import Head from "next/head";

import { useUpdatePostMutation } from "@/services/post";

export default function PostUpdate() {
  // const { data: responseInfo } = useGetAllPostQuery();
  const [updateData, getData] = useUpdatePostMutation();

  console.log("Success: ",getData.isSuccess);
  console.log("Data: ",getData.data);
  
  if (getData.isLoading) return <div>Loading...</div>;
  if (getData.isError) return <h2>An error occured{getData.error.error}</h2>;

  const item = {
   title: "update title",
   body: "update body",
   userId: 12,
   id: 1,
  }

  return (
    <>
      <Head>
        <title>jsonplaceholder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Redux Toolkit - RTK Query (Update Data)</h1>
          <button onClick={() => {updateData(item)}}>Udpate Post</button>
      </div>
    </>
  );
}
